AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    PivotalKey:
        Type: String
    Password:
        Type: String
Resources:
  MyChefServer:
    Type: AWS::OpsWorksCM::Server
    Properties:
      BackupRetentionCount: '12'
      CustomCertificate: '-----BEGIN CERTIFICATE----- EXAMPLEqEXAMPLE== -----END CERTIFICATE-----'
      CustomDomain: 'https://aws.my-company.com'
      CustomPrivateKey: '-----BEGIN RSA PRIVATE KEY----- EXAMPLEqEXAMPLE= -----END RSA PRIVATE KEY-----'
      DisableAutomatedBackup: False
      Engine: 'ChefAutomate'
      EngineVersion: '2'
      EngineAttributes:
          - Name: "CHEF_AUTOMATE_PIVOTAL_KEY"
            Value:
                Ref: PivotalKey
          - Name: "CHEF_AUTOMATE_ADMIN_PASSWORD"
            Value:
                Ref: Password
      EngineModel: 'Single'
      InstanceProfileArn: "INSTANCE-PROFILE-ARN"
      InstanceType: 'r5.xlarge'
      PreferredBackupWindow: '08:00'
      PreferredMaintenanceWindow: 'Fri:08:00'
      ServiceRoleArn: "SERVICE-ROLE-ARN"
      Tags:
          - Key: "Stage"
            Value: "Production"
          - Key: "Name"
            Value: "test-owcm-server"
Outputs:
  endpoint:
    Description: OpsWorksCM Server Endpoint
    Value: !GetAtt [MyChefServer, Endpoint]